/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Maquinaria;

import Objetos.Maquinaria;
import Principal.Home;
import Otros.ConexionSQLServer;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco
 */
public class SeleccionarVehiculo extends javax.swing.JDialog {
    String titulosMaquinaria[]={"Serie","Marca","Modelo","Año","Placas"};
    DefaultTableModel DTMM;
    Connection c = ConexionSQLServer.Conectar();
    String[] datosVehiculo;
    int num;
    public SeleccionarVehiculo(int num,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            System.out.println(e);
        }
        initComponents();
        setLocationRelativeTo(null);
        this.num=num;
        //Tabla de vehículos
        DTMM = new DefaultTableModel(titulosMaquinaria,0);
        tablaVehiculos.setModel(DTMM);
        try{
            Statement smt=c.createStatement();
            ResultSet res= smt.executeQuery("select * from MAQUINARIAS");
            if(res.next()){
                do{
                    Object fila[] = {String.valueOf(Integer.parseInt(res.getString("IDMaquinaria"))),res.getString("Marca"),res.getString("Modelo"),res.getString("Año"),res.getString("Placas")};
                    DTMM.addRow(fila);
                }while(res.next());
                tablaVehiculos.setModel(DTMM);
            }
        }
        catch(SQLException e){
            System.out.println(e);
        }
        Titulo.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        Titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtBuscarVehiculo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Seleccionar vehículo");

        tablaVehiculos.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serie", "Marca", "Modelo", "Año", "Placas"
            }
        ));
        tablaVehiculos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablaVehiculosFocusLost(evt);
            }
        });
        tablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVehiculos);

        Titulo.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        Titulo.setText("Seleccionar vehículo");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/approve-circular-button (1).png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscelaneo/lupa.png"))); // NOI18N

        txtBuscarVehiculo.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        txtBuscarVehiculo.setText("Buscar por serie o modelo...");
        txtBuscarVehiculo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarVehiculoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarVehiculoFocusLost(evt);
            }
        });
        txtBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarVehiculoActionPerformed(evt);
            }
        });
        txtBuscarVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarVehiculoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarVehiculoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(Titulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarVehiculo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Titulo)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscarVehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaVehiculosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaVehiculosFocusLost
        tablaVehiculos.getSelectionModel().clearSelection();
    }//GEN-LAST:event_tablaVehiculosFocusLost

    private void tablaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVehiculosMouseClicked
        datosVehiculo = new String[7];
        int row = tablaVehiculos.getSelectedRow();
        for(int i=0;i<5;i++){
            datosVehiculo[i]=String.valueOf(tablaVehiculos.getValueAt(row, i));
        }
    }//GEN-LAST:event_tablaVehiculosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(datosVehiculo==null){
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún cliente","Aviso",JOptionPane.INFORMATION_MESSAGE);    
        }
        else{
            Maquinaria objCliente = new Maquinaria(datosVehiculo[0],datosVehiculo[1],datosVehiculo[2],datosVehiculo[3],datosVehiculo[4]);
            if(num==0){
                Home.txtVehiculoR.setText(objCliente.getSerie());
                Home.vehiculoD=objCliente;
                Home.check5.setVisible(true);
                this.dispose();
            }
            if(num==1){
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBuscarVehiculoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarVehiculoFocusLost
        if(txtBuscarVehiculo.getText().isEmpty()){
            txtBuscarVehiculo.setText("Buscar por serie o modelo...");
        }
    }//GEN-LAST:event_txtBuscarVehiculoFocusLost

    private void txtBuscarVehiculoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarVehiculoFocusGained
        if(txtBuscarVehiculo.getText().equals("Buscar por serie o modelo...")){
            txtBuscarVehiculo.setText("");
        }
    }//GEN-LAST:event_txtBuscarVehiculoFocusGained

    private void txtBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarVehiculoActionPerformed

    private void txtBuscarVehiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarVehiculoKeyPressed
        DTMM = new DefaultTableModel(titulosMaquinaria,0);
        tablaVehiculos.setModel(DTMM);
        try{
            ResultSet res= mostrar(txtBuscarVehiculo.getText());
            if(res.next()){
                do{
                    Object fila[] = {String.valueOf(Integer.parseInt(res.getString("IDMaquinaria"))),res.getString("Marca"),res.getString("Modelo"),res.getString("Año"),res.getString("Placas")};
                    DTMM.addRow(fila);
                }while(res.next());
                tablaVehiculos.setModel(DTMM);
            }
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtBuscarVehiculoKeyPressed

    private void txtBuscarVehiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarVehiculoKeyReleased
        DTMM = new DefaultTableModel(titulosMaquinaria,0);
        tablaVehiculos.setModel(DTMM);
        try{
            ResultSet res= mostrar(txtBuscarVehiculo.getText());
            if(res.next()){
                do{
                    Object fila[] = {String.valueOf(Integer.parseInt(res.getString("IDMaquinaria"))),res.getString("Marca"),res.getString("Modelo"),res.getString("Año"),res.getString("Placas")};
                    DTMM.addRow(fila);
                }while(res.next());
                tablaVehiculos.setModel(DTMM);
            }
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtBuscarVehiculoKeyReleased
    
    public ResultSet mostrar(String str){
        ResultSet RS=null;
        try{
            Statement ST = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sql = "select * from MAQUINARIAS where IDMaquinaria like '"+str+"%'";
            RS=ST.executeQuery(sql);
        }
        catch(SQLException e){
            System.out.println(e);
        }
        return RS;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            SeleccionarVehiculo dialog = new SeleccionarVehiculo(0,new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTextField txtBuscarVehiculo;
    // End of variables declaration//GEN-END:variables
}
