/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cotizacion;

import Objetos.Producto;
import Otros.ConexionSQLServer;
import Principal.Home;
import static Principal.Home.tablaClientes;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco
 */
public class SeleccionarProducto extends javax.swing.JDialog {

    Connection c = ConexionSQLServer.Conectar();
    String titulosInventario[] = {"Código", "Descripción", "Existencia", "Precio"};
    String titulosInventario2[] = {"Código", "Descripción", "Existencia"};
    DefaultTableModel DTMP, DTMDP;
    String[] datosProducto;
    int num;

    public SeleccionarProducto(int num, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            System.out.println(e);
        }
        initComponents();
        setLocationRelativeTo(null);
        this.num = num;
        //Tabla de inventario
        DTMP = new DefaultTableModel(titulosInventario, 0);
        tablaProductos.setModel(DTMP);
        try {
            Statement smt = c.createStatement();
            ResultSet res = smt.executeQuery("select * from PRODUCTOS");
            if (res.next()) {
                do {
                    Object fila[] = {String.valueOf(Integer.parseInt(res.getString("IDProducto"))), res.getString("Descripcion"), res.getString("Existencia"), res.getString("Precio")};
                    DTMP.addRow(fila);
                } while (res.next());
                tablaProductos.setModel(DTMP);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        Titulo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        Titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtBuscarProduct = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Seleccionar producto");

        tablaProductos.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Existencia", "Precio"
            }
        ));
        tablaProductos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablaProductosFocusLost(evt);
            }
        });
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        Titulo.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        Titulo.setText("Seleccionar producto");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/approve-circular-button (1).png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtBuscarProduct.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        txtBuscarProduct.setText("Buscar por codigo o descripción...");
        txtBuscarProduct.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarProductFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarProductFocusLost(evt);
            }
        });
        txtBuscarProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProductActionPerformed(evt);
            }
        });
        txtBuscarProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarProductKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProductKeyReleased(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscelaneo/lupa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarProduct)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscarProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (datosProducto == null) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún producto", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (num == 1) {
                Producto objCliente = new Producto(datosProducto[0], datosProducto[1], datosProducto[2], datosProducto[3]);
                DTMDP = new DefaultTableModel(titulosInventario, 0);
                Home.tablaDescripcionP.setModel(DTMDP);
                try {
                    Statement smt = c.createStatement();
                    ResultSet res = smt.executeQuery("select * from CLIENTES");
                    if (res.next()) {
                        do {
                            Object fila[] = {objCliente.getCodigo(), objCliente.getDescripcion(), objCliente.getExistencia(), objCliente.getPrecio()};
                            DTMDP.addRow(fila);
                        } while (res.next());
                        Home.tablaDescripcionP.setModel(DTMDP);
                    }
                } catch (SQLException e) {
                    System.out.println(e);
                }
                Home.spCantidad.setEnabled(true);
                Home.agregarP.setEnabled(true);
                this.dispose();
            }
            if (num == 2) {
                Producto objCliente = new Producto(datosProducto[0], datosProducto[1], datosProducto[2], datosProducto[3]);
                DTMDP = new DefaultTableModel(titulosInventario2, 0);
                Home.tablaDescripcionP2.setModel(DTMDP);
                Object fila[] = {objCliente.getCodigo(), objCliente.getDescripcion(), objCliente.getExistencia()};
                DTMDP.addRow(fila);
                Home.tablaDescripcionP2.setModel(DTMDP);
                Home.spCantidad1.setEnabled(true);
                Home.agregarP1.setEnabled(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        datosProducto = new String[7];
        int row = tablaProductos.getSelectedRow();
        for (int i = 0; i < 4; i++) {
            datosProducto[i] = String.valueOf(tablaProductos.getValueAt(row, i));
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void tablaProductosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaProductosFocusLost
        tablaProductos.getSelectionModel().clearSelection();
    }//GEN-LAST:event_tablaProductosFocusLost

    private void txtBuscarProductFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarProductFocusLost
        if (txtBuscarProduct.getText().isEmpty()) {
            txtBuscarProduct.setText("Buscar por codigo o descripción...");
        }
    }//GEN-LAST:event_txtBuscarProductFocusLost

    private void txtBuscarProductFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarProductFocusGained
        if (txtBuscarProduct.getText().equals("Buscar por codigo o descripción...")) {
            txtBuscarProduct.setText("");
        }
    }//GEN-LAST:event_txtBuscarProductFocusGained

    private void txtBuscarProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductActionPerformed

    private void txtBuscarProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductKeyPressed
        DTMP = new DefaultTableModel(titulosInventario, 0);
        tablaProductos.setModel(DTMP);
        ResultSet res = mostrar(txtBuscarProduct.getText());
        try {
            if (res.next()) {
                do {
                    Object fila[] = {String.valueOf(Integer.parseInt(res.getString("IDProducto"))), res.getString("Descripcion"), res.getString("Existencia"), res.getString("Precio")};
                    DTMP.addRow(fila);
                } while (res.next());
                tablaClientes.setModel(DTMP);
            }
        } catch (SQLException e) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_txtBuscarProductKeyPressed

    private void txtBuscarProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductKeyReleased
        DTMP = new DefaultTableModel(titulosInventario, 0);
        tablaProductos.setModel(DTMP);
        ResultSet res = mostrar(txtBuscarProduct.getText());
        try {
            if (res.next()) {
                do {
                    Object fila[] = {String.valueOf(Integer.parseInt(res.getString("IDProducto"))), res.getString("Descripcion"), res.getString("Existencia"), res.getString("Precio")};
                    DTMP.addRow(fila);
                } while (res.next());
                tablaClientes.setModel(DTMP);
            }
        } catch (SQLException e) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_txtBuscarProductKeyReleased

    public ResultSet mostrar(String str) {
        ResultSet RS = null;
        try {
            Statement ST = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sql = "select * from PRODUCTOS where IDProducto like '" + str + "%'";
            RS = ST.executeQuery(sql);
        } catch (SQLException e) {
            System.out.println(e);
        }
        return RS;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            SeleccionarProducto dialog = new SeleccionarProducto(0,new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtBuscarProduct;
    // End of variables declaration//GEN-END:variables
}
