/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedores;

import Otros.ConexionSQLServer;
import static Principal.Home.tablaCC1;
import static Principal.Home.tablaCC2;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco
 */

public class SeleccionarObra extends javax.swing.JDialog {
    String titulosObraS[]={"Matricula","Nombre","Cliente"};
    DefaultTableModel DTMC;
    Connection c = ConexionSQLServer.Conectar();
    String[] datosObraS;
    int num;
    DefaultTableModel DTMO;
    int row;

    public SeleccionarObra(int num,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            System.out.println(e);
        }
        initComponents();
        setLocationRelativeTo(null);
        this.num=num;
//        Tabla de clientes
        DTMC = new DefaultTableModel(titulosObraS,0);
        tablaProveedorS.setModel(DTMC);
        try{
            Statement smt=c.createStatement();
            ResultSet res= smt.executeQuery("select IDObra,NombreObra,cliente from OBRAS");
            if(res.next()){
                do{
                    ResultSet res2 = mostrar2(res.getString("Cliente"));
                    if(res2.next()){
                    Object fila[] = {String.valueOf(Integer.parseInt(res.getString("IDObra"))),res.getString("NombreObra"),res2.getString("Nombre")+" "+res2.getString("Apellido")};
                    DTMC.addRow(fila);
                    }
                }while(res.next()); 
            tablaProveedorS.setModel(DTMC); 
            } 
        }
        catch(SQLException e){
            System.out.println(e);
        }
        Titulo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedorS = new javax.swing.JTable();
        Titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtBuscar2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Seleccionar obra");

        tablaProveedorS.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        tablaProveedorS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matricula", "Nombre", "Cliente"
            }
        ));
        tablaProveedorS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablaProveedorSFocusLost(evt);
            }
        });
        tablaProveedorS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveedorSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProveedorS);

        Titulo.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        Titulo.setText("Seleccionar obra");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/approve-circular-button (1).png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtBuscar2.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        txtBuscar2.setText("Buscar por cliente, nombre o matricula de obra...");
        txtBuscar2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscar2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscar2FocusLost(evt);
            }
        });
        txtBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar2ActionPerformed(evt);
            }
        });
        txtBuscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscar2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscar2KeyReleased(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miscelaneo/lupa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(Titulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public ResultSet mostrar2(String str){
        ResultSet RS=null;
        try{
            Statement ST = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sql = "select Nombre,Apellido from CLIENTES where IDCliente='"+str+"'";
            RS=ST.executeQuery(sql);
        }
        catch(SQLException e){
            System.out.println(e);
        }
        return RS;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(datosObraS==null){
            JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna obra","Aviso",JOptionPane.INFORMATION_MESSAGE);    
        }
        else{
            if(num==0){
                AgregarPago.txtObraS.setText(datosObraS[1]);
                AgregarPago.txtObraS.setText(datosObraS[1]+" "+datosObraS[2]);
                AgregarPago.check7.setVisible(true);
                AgregarPago.obra=datosObraS[0];
                this.dispose();
            }
            if(num==1){
                DTMC = new DefaultTableModel(titulosObraS,0);
                tablaCC1.setModel(DTMC);
                try{
                    Statement smt=c.createStatement();
                    ResultSet res= smt.executeQuery("select IDObra,NombreObra,cliente from OBRAS");
                    if(res.next()){
                        do{
                            Object fila[] = {String.valueOf(Integer.parseInt(res.getString("IDObra"))),res.getString("NombreObra"),res.getString("Cliente")};
                            DTMC.addRow(fila);
                        }while(res.next());
                        tablaCC1.setModel(DTMC);
                    }
                }
                catch(SQLException e){
                    System.out.println("Error");
                }
                this.dispose();
            }
            if(num==2){
                Obras.AgregarSeguimiento.txtObraS.setText(datosObraS[1]+" "+datosObraS[2]);
                Obras.AgregarSeguimiento.check6.setVisible(true);
                Obras.AgregarSeguimiento.obraSS=datosObraS[0];
                this.dispose();
            }
            if(num==3){
                DTMC = new DefaultTableModel(titulosObraS,0);
                tablaCC2.setModel(DTMC);
                try{
                    Statement smt=c.createStatement();
                    ResultSet res= smt.executeQuery("select IDObra,NombreObra,cliente from OBRAS where IDObra='"+tablaProveedorS.getValueAt(row,0)+"'");
                    if(res.next()){
                        ResultSet res2 = mostrar2(res.getString("Cliente"));
                        if(res2.next()){
                            do{
                                Object fila[] = {String.valueOf(Integer.parseInt(res.getString("IDObra"))),res.getString("NombreObra"),res2.getString("Nombre")+" "+res2.getString("Apellido")};
                                DTMC.addRow(fila);
                            }while(res.next());
                        }
                    tablaCC2.setModel(DTMC); 
                    } 
                }
                catch(SQLException e){
                    System.out.println(e);
                }
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBuscar2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscar2FocusLost
        if(txtBuscar2.getText().isEmpty()){
            txtBuscar2.setText("Buscar por cliente, nombre o matricula de obra...");
        }
    }//GEN-LAST:event_txtBuscar2FocusLost

    private void txtBuscar2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscar2FocusGained
        if(txtBuscar2.getText().equals("Buscar por cliente, nombre o matricula de obra...")){
            txtBuscar2.setText("");
        }
    }//GEN-LAST:event_txtBuscar2FocusGained

    private void txtBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar2ActionPerformed

    private void tablaProveedorSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedorSMouseClicked
        datosObraS = new String[5];
        row = tablaProveedorS.getSelectedRow();
        for(int i=0;i<3;i++){
            datosObraS[i]=String.valueOf(tablaProveedorS.getValueAt(row, i));
        }
    }//GEN-LAST:event_tablaProveedorSMouseClicked

    private void tablaProveedorSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablaProveedorSFocusLost
        tablaProveedorS.getSelectionModel().clearSelection();
    }//GEN-LAST:event_tablaProveedorSFocusLost

    private void txtBuscar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar2KeyPressed
        DTMO = new DefaultTableModel(titulosObraS,0);
        tablaProveedorS.setModel(DTMO);
        ResultSet res = mostrar(txtBuscar2.getText());
        try{
            if(res.next()){
                do{
                    Object fila[] = {res.getString("IDObra"),res.getString("NombreObra"),res.getString("Cliente")};
                    DTMO.addRow(fila);
                }while(res.next());
                tablaProveedorS.setModel(DTMO);
            }
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtBuscar2KeyPressed

    private void txtBuscar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar2KeyReleased
        DTMO = new DefaultTableModel(titulosObraS,0);
        tablaProveedorS.setModel(DTMO);
        ResultSet res = mostrar(txtBuscar2.getText());
        try{
            if(res.next()){
                do{
                    Object fila[] = {res.getString("IDObra"),res.getString("NombreObra"),res.getString("Cliente")};
                    DTMO.addRow(fila);
                }while(res.next());
                tablaProveedorS.setModel(DTMO);
            }
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtBuscar2KeyReleased
    
    public ResultSet mostrar(String str){
        ResultSet RS=null;
        try{
            Statement ST = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sql = "select IDObra,NombreObra,cliente from OBRAS where IDObra like '"+str+"%'";
            RS=ST.executeQuery(sql);
        }
        catch(SQLException e){
            System.out.println(e);
        }
        return RS;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            SeleccionarObra dialog = new SeleccionarObra(0,new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedorS;
    private javax.swing.JTextField txtBuscar2;
    // End of variables declaration//GEN-END:variables
}
